version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    ports:
      - "8000:8000"
    environment:
      - PERSISTENCE_TYPE=sql
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=diagnosis_ai
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: