name: Manual Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy-api:
    name: Manual API Deployment
    uses: ./.github/workflows/deploy-api.yml
    secrets: inherit
