name: Test Python API

on:
  push:
    branches: [main, develop]
    paths:
      - 'diagnosis-ai-api/**'
      - '.github/workflows/test-api.yml'
  pull_request:
    branches: [main]
    paths:
      - 'diagnosis-ai-api/**'
      - '.github/workflows/test-api.yml'
  workflow_call:
    outputs:
      test-result:
        description: 'Result of API tests'
        value: ${{ jobs.test-api.outputs.result }}

env:
  PYTHON_VERSION: '3.12'

jobs:
  test-api:
    name: Test Python API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./diagnosis-ai-api
    outputs:
      result: ${{ steps.test.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests with pytest
        id: test
        env:
          GEMINI_API_KEY: test-api-key-for-testing  # Mock API key for testing
          DATABASE_URL: postgresql://test:test@localhost:5432/test  # Mock DB URL for testing
        run: |
          uv run pytest --cov=src --cov-report=xml --cov-report=term-missing --tb=short

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./diagnosis-ai-api/coverage.xml
          flags: api-tests
          name: api-coverage
          fail_ci_if_error: false
